apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-external
  name: db-external
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP