apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "50%"
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      # changed this from python:latest to test rollouts
      - image: python:3.12
        name: frontend
        command: ["sh", "-c", "cd /repo && pip install --no-cache-dir -r app/requirements.txt && python -m app.frontend.main"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http-port
        env:
        # Set to False to stop health check failures, True to continue
        - name: FAIL_HEALTHCHECK
          value: "False"
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 60
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          periodSeconds: 1
          initialDelaySeconds: 0
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 1
          failureThreshold: 30
        volumeMounts:
        - name: repo-volume
          mountPath: /repo
      initContainers:
      - name: init-repo
        image: ubuntu:latest
        env:
        - name: REPO
          valueFrom:
            configMapKeyRef:
              key: repo 
              name: git-config
        - name: USER
          valueFrom:
            configMapKeyRef:
              key: username
              name: git-config
        - name: DESTINATION
          valueFrom:
            configMapKeyRef:
              key: destination
              name: git-config
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: git-creds
        command:
          - bash
          - -c
          - |
            apt-get update && apt-get install -y git
            git clone https://$USER:$TOKEN@github.com/$USER/$REPO.git $DESTINATION
        volumeMounts:
        - mountPath: /repo
          name: repo-volume
    
      volumes:
      - name: repo-volume
        emptyDir:
          sizeLimit: 500Mi
