apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: backend-db-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db-secret-access
subjects:
- kind: ServiceAccount
  name: backend
  namespace: default
