apiVersion: v1
kind: Service
metadata: 
  name: test-deployment-nginx
  labels:
    app: test-deployment
spec:
  selector:
    app: test-deployment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
