apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: python:latest
        name: backend
        command: ["sh", "-c", "cd /repo && pip install --no-cache-dir -r app/requirements.txt && python -m app.backend.main"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 60
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          periodSeconds: 1
          initialDelaySeconds: 0
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 1
          failureThreshold: 90
        env:
        # Set to False to stop health check failures, True to continue
        - name: FAIL_HEALTHCHECK
          value: "False"
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: DB_PORT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: key
        volumeMounts:
          - name: repo-volume
            mountPath: /repo
      initContainers:
        - name: init-repo
          image: ubuntu:latest
          env:
          - name: REPO
            valueFrom:
              configMapKeyRef:
                name: git-config
                key: repo
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: git-config
                key: username
          - name: DESTINATION
            valueFrom:
              configMapKeyRef:
                name: git-config
                key: destination
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: git-creds
                key: token
          command:
          - bash
          - -c
          - |
            apt-get update && apt-get install -y git
            git clone https://$USER:$TOKEN@github.com/$USER/$REPO.git $DESTINATION
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      volumes:
        - name: repo-volume
          emptyDir:
            sizeLimit: 500Mi
