apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-external
  name: backend-external
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: NodePort